### ISSUE TITLE
[Suggestion] Test the message

### ISSUE THREAD

**Issue by ooTruffle** [Mister-42/mr42-cogs#3]
Would there be a way to re add from tube the 'Test' command that Grabs the latest video and posts it to the set channel to let us test if its working and how the message works

**Comment by Mister-42** [comment]
I'd have to find a way to implement this properly, especially with many channels in the configuration.  With a big configuration, such test messages would very quickly reach the rate limit and block normal functionality.

Additionally, Tube processes YouTube channels per Discord server, where this cog retrieves any YouTube channel just once and then sends the messages (even to multiple channels/servers). It requires a completely different logic to send test message for just one Discord server. It's not impossible, but challenging.

**Comment by ooTruffle** [comment]
Would there be a way to just test the msg without touching the api?

It just sends a msg to the current channel with the ping and a test embed (no yt link and it just uses placeholders

**Comment by Mister-42** [comment]
Compromising, hit the feed for the Official YouTube channel, load the latest 1 video and post :) Ping and custom message hardcoded for the test.
