### ISSUE TITLE
🚫 Unable to retrieve channel id from **

### ISSUE THREAD

**Issue by Norien** [Mister-42/mr42-cogs#4]
Not sure what I'm doing wrong but it can never resolve the channel id 

```!youtube publish https://youtube.com/@t-me8295```

🚫 Unable to retrieve channel id from **https://youtube.com/@t-me8295**

I guess it's also not clear to me the difference between subscribe and publish 🤦‍♂️

Thank you for your time.

**Comment by Mister-42** [comment]
The 'new' channel names starting with @ are not supported yet in the upstream library `PyTube` used in this project. I have been looking for a solution, but haven't found one just yet.

`subscribe` is adding a youtube channel to the list to post in a Discord channel
`publish` is something Discord specific, described [here](https://support.discord.com/hc/en-us/articles/360032008192-Announcement-Channels-).

**Comment by Mister-42** [comment]
What you can you for the @ channels is simple copy the url of their latest video or something. Most of it works

`!youtube subscribe https://www.youtube.com/watch?v=Oqy9eup-qAE`
