### ISSUE TITLE
Not fetching or posting new videos

### ISSUE THREAD

**Issue by Norien** [Mister-42/mr42-cogs#5]
Bot has admin, permission seems correct as bot will post an old video correctly upon reboot.

New videos are not being posted.

Interval is set to check every 15 mins and bot confirms.

Upon reboot an old video will be posted in the correctly set channel.

```
[2023-09-19 15:09:04] [ERROR] discord.ext.tasks: Unhandled exception in internal background task 'background_get_new_videos'.
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/discord/ext/tasks/__init__.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "/root/.local/share/Red-DiscordBot/data/mybot/cogs/CogManager/cogs/youtube/youtube.py", line 676, in background_get_new_videos
    await self.send_message(entry, channel, dchans)
  File "/root/.local/share/Red-DiscordBot/data/mybot/cogs/CogManager/cogs/youtube/youtube.py", line 718, in send_message
    message = await channel.send(role, file=icon, embed=embed, allowed_mentions=mentions)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/discord/abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/discord/http.py", line 739, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
```

**Comment by Mister-42** [comment]
I might need to add an additional check for `attach_files` and `mention_everyone` permissions, but you say the bot has admin right already. So that should not be the issue here. Discord says your bot is forbidden from posting the embed. *insert confused face*

What does `!yt test` give you?

**Comment by Mister-42** [comment]
I added one permission check in https://github.com/Mister-42/mr42-cogs/commit/d1423bc86b71bb064fb138962293f4be0471aa86. Can you please update and try again?

**Comment by Norien** [comment]
> I might need to add an additional check for `attach_files` and `mention_everyone` permissions, but you say the bot has admin right already. So that should not be the issue here. Discord says your bot is forbidden from posting the embed. _insert confused face_
> 
> What does `!yt test` give you?

![Screenshot_20230919-122541](https://github.com/Mister-42/mr42-cogs/assets/8930713/0e85e9ee-55c8-4c34-a806-49705ab0ccb9)

**Comment by Norien** [comment]
Just updated and immediately 4 of the newest videos were posted!

**Comment by Mister-42** [comment]
I'm a bit confused by the mixed results, but I did crush a bug after all :)

**Comment by Norien** [comment]
I appreciate your prompt response! I will report back if the next uploaded video gets posted correctly.

**Comment by Norien** [comment]
Newest video was posted as expected. Thank you again! ❤️
