### ISSUE TITLE
Unable to retrieve channel id from...

### ISSUE THREAD

**Issue by ghost** [Mister-42/mr42-cogs#6]
So it seems to work flawlessly for some youtube channels, but then some others it returns this error. For reference, I'm adding them to the same channel on Discord.

**THIS WORKED:**
!yt subscribe https://www.youtube.com/@BellularGaming/ #world-of-warcraft
✅ The YouTube channel Bellular Warcraft will now be announced in ⁠world-of-warcraft when new videos are published.

**THIS DID NOT WORK:**
!yt subscribe https://www.youtube.com/@MrGM/ ⁠#world-of-warcraft
🚫 Unable to retrieve channel id from https://www.youtube.com/@MrGM/.

**Comment by ghost** [comment]
Seems to be more of an issue on Youtube's side as it turns out. If you search for MrGM channel on youtube, that will be the link that it gives you. However, we've worked out that the true URL is in fact: https://www.youtube.com/user/MrGamemasterReviews

Not sure if there is a workaround possible for the cog or not? I guess this will be an issue for any accounts that have changed their youtube handle at some point.

**Comment by Mister-42** [comment]
Wow, that's odd YouTube behaviour.
I don't think I can get a workaround for this, as no information is returned at all

```
--2024-04-02 10:08:23--  https://www.youtube.com/@MrGM/
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving www.youtube.com (www.youtube.com)... 2a00:1450:4001:80f::200e, 2a00:1450:4001:810::200e, 2a00:1450:4001:801::200e, ...
Connecting to www.youtube.com (www.youtube.com)|2a00:1450:4001:80f::200e|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://www.youtube.com/MrGM [following]
--2024-04-02 10:08:23--  https://www.youtube.com/MrGM
Reusing existing connection to [www.youtube.com]:443.
HTTP request sent, awaiting response... 404 Not Found
2024-04-02 10:08:23 ERROR 404: Not Found.
```
